version: '3.4'

services:
  repository:
    image: repository
    build:
      context: laravel
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
